// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

/**
 * Protobuf enum {@code ru.dmrval.entity.AccountType}
 */
public enum AccountType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GOLD = 0;</code>
   */
  GOLD(0),
  /**
   * <code>PREMIUM = 1;</code>
   */
  PREMIUM(1),
  /**
   * <code>BASE = 2;</code>
   */
  BASE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GOLD = 0;</code>
   */
  public static final int GOLD_VALUE = 0;
  /**
   * <code>PREMIUM = 1;</code>
   */
  public static final int PREMIUM_VALUE = 1;
  /**
   * <code>BASE = 2;</code>
   */
  public static final int BASE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AccountType valueOf(int value) {
    return forNumber(value);
  }

  public static AccountType forNumber(int value) {
    switch (value) {
      case 0: return GOLD;
      case 1: return PREMIUM;
      case 2: return BASE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AccountType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AccountType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AccountType>() {
          public AccountType findValueByNumber(int number) {
            return AccountType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ru.dmrval.entity.BankAccountInfoOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final AccountType[] VALUES = values();

  public static AccountType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AccountType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ru.dmrval.entity.AccountType)
}

