// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

public final class BankAccountInfoOuterClass {
  private BankAccountInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_dmrval_entity_BankAccountInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_dmrval_entity_BankAccountInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_dmrval_entity_BankAccountInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_dmrval_entity_BankAccountInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_dmrval_entity_BankAccountInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_dmrval_entity_BankAccountInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_dmrval_entity_BankAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_dmrval_entity_BankAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_dmrval_entity_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_dmrval_entity_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BankAccountInfo.proto\022\020ru.dmrval.entit" +
      "y\"*\n\026BankAccountInfoRequest\022\020\n\010typeName\030" +
      "\001 \001(\t\"U\n\027BankAccountInfoResponse\022:\n\017bank" +
      "AccountInfo\030\001 \003(\0132!.ru.dmrval.entity.Ban" +
      "kAccountInfo\"q\n\017BankAccountInfo\022*\n\007addre" +
      "ss\030\001 \001(\0132\031.ru.dmrval.entity.Address\0222\n\013b" +
      "ankAccount\030\002 \001(\0132\035.ru.dmrval.entity.Bank" +
      "Account\"\230\001\n\013BankAccount\022\014\n\004uuid\030\001 \001(\t\022\021\n" +
      "\tfirstName\030\002 \001(\t\022\020\n\010lastName\030\003 \001(\t\022\022\n\npa" +
      "tronymic\030\004 \001(\t\022\025\n\raccountNumber\030\005 \001(\003\022+\n" +
      "\004type\030\006 \001(\0162\035.ru.dmrval.entity.AccountTy" +
      "pe\"6\n\007Address\022\016\n\006street\030\001 \001(\t\022\014\n\004city\030\002 " +
      "\001(\t\022\r\n\005state\030\003 \001(\t*.\n\013AccountType\022\010\n\004GOL" +
      "D\020\000\022\013\n\007PREMIUM\020\001\022\010\n\004BASE\020\0022\202\001\n\026BankAccou" +
      "ntInfoService\022h\n\021getAccountsByType\022(.ru." +
      "dmrval.entity.BankAccountInfoRequest\032).r" +
      "u.dmrval.entity.BankAccountInfoResponseB" +
      "\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ru_dmrval_entity_BankAccountInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_dmrval_entity_BankAccountInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_dmrval_entity_BankAccountInfoRequest_descriptor,
        new java.lang.String[] { "TypeName", });
    internal_static_ru_dmrval_entity_BankAccountInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_dmrval_entity_BankAccountInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_dmrval_entity_BankAccountInfoResponse_descriptor,
        new java.lang.String[] { "BankAccountInfo", });
    internal_static_ru_dmrval_entity_BankAccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ru_dmrval_entity_BankAccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_dmrval_entity_BankAccountInfo_descriptor,
        new java.lang.String[] { "Address", "BankAccount", });
    internal_static_ru_dmrval_entity_BankAccount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ru_dmrval_entity_BankAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_dmrval_entity_BankAccount_descriptor,
        new java.lang.String[] { "Uuid", "FirstName", "LastName", "Patronymic", "AccountNumber", "Type", });
    internal_static_ru_dmrval_entity_Address_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ru_dmrval_entity_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_dmrval_entity_Address_descriptor,
        new java.lang.String[] { "Street", "City", "State", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
