// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

public interface BankAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.dmrval.entity.BankAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>string firstName = 2;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 3;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string patronymic = 4;</code>
   */
  java.lang.String getPatronymic();
  /**
   * <code>string patronymic = 4;</code>
   */
  com.google.protobuf.ByteString
      getPatronymicBytes();

  /**
   * <code>int64 accountNumber = 5;</code>
   */
  long getAccountNumber();

  /**
   * <code>.ru.dmrval.entity.AccountType type = 6;</code>
   */
  int getTypeValue();
  /**
   * <code>.ru.dmrval.entity.AccountType type = 6;</code>
   */
  ru.dmrval.entity.AccountType getType();
}
