// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

public interface BankAccountInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.dmrval.entity.BankAccountInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ru.dmrval.entity.Address address = 1;</code>
   */
  boolean hasAddress();
  /**
   * <code>.ru.dmrval.entity.Address address = 1;</code>
   */
  ru.dmrval.entity.Address getAddress();
  /**
   * <code>.ru.dmrval.entity.Address address = 1;</code>
   */
  ru.dmrval.entity.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
   */
  boolean hasBankAccount();
  /**
   * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
   */
  ru.dmrval.entity.BankAccount getBankAccount();
  /**
   * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
   */
  ru.dmrval.entity.BankAccountOrBuilder getBankAccountOrBuilder();
}
