// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.dmrval.entity.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string street = 1;</code>
   */
  java.lang.String getStreet();
  /**
   * <code>string street = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <code>string city = 2;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 2;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 3;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 3;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
