// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

public interface BankAccountInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.dmrval.entity.BankAccountInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string typeName = 1;</code>
   */
  java.lang.String getTypeName();
  /**
   * <code>string typeName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeNameBytes();
}
