// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

public interface BankAccountInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.dmrval.entity.BankAccountInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ru.dmrval.entity.BankAccountInfo bankAccountInfo = 1;</code>
   */
  java.util.List<ru.dmrval.entity.BankAccountInfo> 
      getBankAccountInfoList();
  /**
   * <code>repeated .ru.dmrval.entity.BankAccountInfo bankAccountInfo = 1;</code>
   */
  ru.dmrval.entity.BankAccountInfo getBankAccountInfo(int index);
  /**
   * <code>repeated .ru.dmrval.entity.BankAccountInfo bankAccountInfo = 1;</code>
   */
  int getBankAccountInfoCount();
  /**
   * <code>repeated .ru.dmrval.entity.BankAccountInfo bankAccountInfo = 1;</code>
   */
  java.util.List<? extends ru.dmrval.entity.BankAccountInfoOrBuilder> 
      getBankAccountInfoOrBuilderList();
  /**
   * <code>repeated .ru.dmrval.entity.BankAccountInfo bankAccountInfo = 1;</code>
   */
  ru.dmrval.entity.BankAccountInfoOrBuilder getBankAccountInfoOrBuilder(
      int index);
}
