// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BankAccountInfo.proto

package ru.dmrval.entity;

/**
 * Protobuf type {@code ru.dmrval.entity.BankAccountInfo}
 */
public  final class BankAccountInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.dmrval.entity.BankAccountInfo)
    BankAccountInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BankAccountInfo.newBuilder() to construct.
  private BankAccountInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BankAccountInfo() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BankAccountInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ru.dmrval.entity.Address.Builder subBuilder = null;
            if (address_ != null) {
              subBuilder = address_.toBuilder();
            }
            address_ = input.readMessage(ru.dmrval.entity.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(address_);
              address_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            ru.dmrval.entity.BankAccount.Builder subBuilder = null;
            if (bankAccount_ != null) {
              subBuilder = bankAccount_.toBuilder();
            }
            bankAccount_ = input.readMessage(ru.dmrval.entity.BankAccount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bankAccount_);
              bankAccount_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.dmrval.entity.BankAccountInfoOuterClass.internal_static_ru_dmrval_entity_BankAccountInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.dmrval.entity.BankAccountInfoOuterClass.internal_static_ru_dmrval_entity_BankAccountInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.dmrval.entity.BankAccountInfo.class, ru.dmrval.entity.BankAccountInfo.Builder.class);
  }

  public static final int ADDRESS_FIELD_NUMBER = 1;
  private ru.dmrval.entity.Address address_;
  /**
   * <code>.ru.dmrval.entity.Address address = 1;</code>
   */
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.ru.dmrval.entity.Address address = 1;</code>
   */
  public ru.dmrval.entity.Address getAddress() {
    return address_ == null ? ru.dmrval.entity.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.ru.dmrval.entity.Address address = 1;</code>
   */
  public ru.dmrval.entity.AddressOrBuilder getAddressOrBuilder() {
    return getAddress();
  }

  public static final int BANKACCOUNT_FIELD_NUMBER = 2;
  private ru.dmrval.entity.BankAccount bankAccount_;
  /**
   * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
   */
  public boolean hasBankAccount() {
    return bankAccount_ != null;
  }
  /**
   * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
   */
  public ru.dmrval.entity.BankAccount getBankAccount() {
    return bankAccount_ == null ? ru.dmrval.entity.BankAccount.getDefaultInstance() : bankAccount_;
  }
  /**
   * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
   */
  public ru.dmrval.entity.BankAccountOrBuilder getBankAccountOrBuilder() {
    return getBankAccount();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (address_ != null) {
      output.writeMessage(1, getAddress());
    }
    if (bankAccount_ != null) {
      output.writeMessage(2, getBankAccount());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (address_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAddress());
    }
    if (bankAccount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBankAccount());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.dmrval.entity.BankAccountInfo)) {
      return super.equals(obj);
    }
    ru.dmrval.entity.BankAccountInfo other = (ru.dmrval.entity.BankAccountInfo) obj;

    boolean result = true;
    result = result && (hasAddress() == other.hasAddress());
    if (hasAddress()) {
      result = result && getAddress()
          .equals(other.getAddress());
    }
    result = result && (hasBankAccount() == other.hasBankAccount());
    if (hasBankAccount()) {
      result = result && getBankAccount()
          .equals(other.getBankAccount());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasBankAccount()) {
      hash = (37 * hash) + BANKACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getBankAccount().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.dmrval.entity.BankAccountInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.dmrval.entity.BankAccountInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.dmrval.entity.BankAccountInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.dmrval.entity.BankAccountInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.dmrval.entity.BankAccountInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.dmrval.entity.BankAccountInfo)
      ru.dmrval.entity.BankAccountInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.dmrval.entity.BankAccountInfoOuterClass.internal_static_ru_dmrval_entity_BankAccountInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.dmrval.entity.BankAccountInfoOuterClass.internal_static_ru_dmrval_entity_BankAccountInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.dmrval.entity.BankAccountInfo.class, ru.dmrval.entity.BankAccountInfo.Builder.class);
    }

    // Construct using ru.dmrval.entity.BankAccountInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        address_ = null;
        addressBuilder_ = null;
      }
      if (bankAccountBuilder_ == null) {
        bankAccount_ = null;
      } else {
        bankAccount_ = null;
        bankAccountBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.dmrval.entity.BankAccountInfoOuterClass.internal_static_ru_dmrval_entity_BankAccountInfo_descriptor;
    }

    @java.lang.Override
    public ru.dmrval.entity.BankAccountInfo getDefaultInstanceForType() {
      return ru.dmrval.entity.BankAccountInfo.getDefaultInstance();
    }

    @java.lang.Override
    public ru.dmrval.entity.BankAccountInfo build() {
      ru.dmrval.entity.BankAccountInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.dmrval.entity.BankAccountInfo buildPartial() {
      ru.dmrval.entity.BankAccountInfo result = new ru.dmrval.entity.BankAccountInfo(this);
      if (addressBuilder_ == null) {
        result.address_ = address_;
      } else {
        result.address_ = addressBuilder_.build();
      }
      if (bankAccountBuilder_ == null) {
        result.bankAccount_ = bankAccount_;
      } else {
        result.bankAccount_ = bankAccountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.dmrval.entity.BankAccountInfo) {
        return mergeFrom((ru.dmrval.entity.BankAccountInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.dmrval.entity.BankAccountInfo other) {
      if (other == ru.dmrval.entity.BankAccountInfo.getDefaultInstance()) return this;
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.hasBankAccount()) {
        mergeBankAccount(other.getBankAccount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ru.dmrval.entity.BankAccountInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ru.dmrval.entity.BankAccountInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ru.dmrval.entity.Address address_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.dmrval.entity.Address, ru.dmrval.entity.Address.Builder, ru.dmrval.entity.AddressOrBuilder> addressBuilder_;
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public boolean hasAddress() {
      return addressBuilder_ != null || address_ != null;
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public ru.dmrval.entity.Address getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? ru.dmrval.entity.Address.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public Builder setAddress(ru.dmrval.entity.Address value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public Builder setAddress(
        ru.dmrval.entity.Address.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public Builder mergeAddress(ru.dmrval.entity.Address value) {
      if (addressBuilder_ == null) {
        if (address_ != null) {
          address_ =
            ru.dmrval.entity.Address.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        address_ = null;
        addressBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public ru.dmrval.entity.Address.Builder getAddressBuilder() {
      
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    public ru.dmrval.entity.AddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            ru.dmrval.entity.Address.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>.ru.dmrval.entity.Address address = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.dmrval.entity.Address, ru.dmrval.entity.Address.Builder, ru.dmrval.entity.AddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.dmrval.entity.Address, ru.dmrval.entity.Address.Builder, ru.dmrval.entity.AddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private ru.dmrval.entity.BankAccount bankAccount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.dmrval.entity.BankAccount, ru.dmrval.entity.BankAccount.Builder, ru.dmrval.entity.BankAccountOrBuilder> bankAccountBuilder_;
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public boolean hasBankAccount() {
      return bankAccountBuilder_ != null || bankAccount_ != null;
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public ru.dmrval.entity.BankAccount getBankAccount() {
      if (bankAccountBuilder_ == null) {
        return bankAccount_ == null ? ru.dmrval.entity.BankAccount.getDefaultInstance() : bankAccount_;
      } else {
        return bankAccountBuilder_.getMessage();
      }
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public Builder setBankAccount(ru.dmrval.entity.BankAccount value) {
      if (bankAccountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bankAccount_ = value;
        onChanged();
      } else {
        bankAccountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public Builder setBankAccount(
        ru.dmrval.entity.BankAccount.Builder builderForValue) {
      if (bankAccountBuilder_ == null) {
        bankAccount_ = builderForValue.build();
        onChanged();
      } else {
        bankAccountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public Builder mergeBankAccount(ru.dmrval.entity.BankAccount value) {
      if (bankAccountBuilder_ == null) {
        if (bankAccount_ != null) {
          bankAccount_ =
            ru.dmrval.entity.BankAccount.newBuilder(bankAccount_).mergeFrom(value).buildPartial();
        } else {
          bankAccount_ = value;
        }
        onChanged();
      } else {
        bankAccountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public Builder clearBankAccount() {
      if (bankAccountBuilder_ == null) {
        bankAccount_ = null;
        onChanged();
      } else {
        bankAccount_ = null;
        bankAccountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public ru.dmrval.entity.BankAccount.Builder getBankAccountBuilder() {
      
      onChanged();
      return getBankAccountFieldBuilder().getBuilder();
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    public ru.dmrval.entity.BankAccountOrBuilder getBankAccountOrBuilder() {
      if (bankAccountBuilder_ != null) {
        return bankAccountBuilder_.getMessageOrBuilder();
      } else {
        return bankAccount_ == null ?
            ru.dmrval.entity.BankAccount.getDefaultInstance() : bankAccount_;
      }
    }
    /**
     * <code>.ru.dmrval.entity.BankAccount bankAccount = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.dmrval.entity.BankAccount, ru.dmrval.entity.BankAccount.Builder, ru.dmrval.entity.BankAccountOrBuilder> 
        getBankAccountFieldBuilder() {
      if (bankAccountBuilder_ == null) {
        bankAccountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.dmrval.entity.BankAccount, ru.dmrval.entity.BankAccount.Builder, ru.dmrval.entity.BankAccountOrBuilder>(
                getBankAccount(),
                getParentForChildren(),
                isClean());
        bankAccount_ = null;
      }
      return bankAccountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.dmrval.entity.BankAccountInfo)
  }

  // @@protoc_insertion_point(class_scope:ru.dmrval.entity.BankAccountInfo)
  private static final ru.dmrval.entity.BankAccountInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.dmrval.entity.BankAccountInfo();
  }

  public static ru.dmrval.entity.BankAccountInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BankAccountInfo>
      PARSER = new com.google.protobuf.AbstractParser<BankAccountInfo>() {
    @java.lang.Override
    public BankAccountInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BankAccountInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BankAccountInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BankAccountInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.dmrval.entity.BankAccountInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

